# Generated by Django 5.2.1 on 2025-05-18 04:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_notification'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Notification',
        ),
    ]
